version: 2

updates:
  - package-ecosystem: "github-actions"
    labels:
      - "bot:github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "cargo"
    labels:
      - "bot:dependencies"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    labels:
      - "bot:dependencies"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    labels:
      - "bot:dependencies"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

registries:
  github:
    type: git
    url: https://github.com
    username: MidnightCI
    password: ${{ secrets.MIDNIGHTCI_REPO }}
